"""baseline — current full schema

Revision ID: 0001_baseline
Revises:
Create Date: 2026-06-08

This baseline materialises the entire current schema via metadata.create_all,
which is idempotent (it skips tables that already exist). That makes it safe on
both a fresh DB (creates everything) and the existing production DB (no-op).

On an EXISTING database, run `alembic stamp head` once to mark this baseline as
applied without re-running it. New schema changes from here on should be real
autogenerated migrations (`alembic revision --autogenerate -m "..."`), gradually
replacing the create_all + _SCHEMA_PATCHES bootstrap in main.py.
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    from database import Base
    import models  # noqa: F401 — ensure every model is registered on Base.metadata
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    # The baseline is not reversible (we don't drop the whole schema).
    pass
